spellchecker: aspell
matrix:
  - name: quarto
    pipeline:
      - pyspelling.filters.markdown
    sources:
      - '**/*.qmd'
  - name: python
    pipeline:
      - pyspelling.filters.python
    sources:
      - '**/*.py'
  - name: build
    pipeline:
      - pyspelling.filters.html:
          ignores:
            - code
            - pre
    sources:
      - '**/*.py'
