---
project:
  type: website
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
lib-dir: ./assets
jupyter: python3
website:
  title: "acederberg.io"
  site-url: https://quarto.acederberg.io
  description: "acederberg's quarto projects"

  # NOTE: https://icons.getbootstrap.com/
  navbar:
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - icon: house
        href: https://acederberg.io
      - text: posts
        href: /posts
      - text: resume
        href: https://acederberg.io/resume

# style: 
#   html:
theme:
  dark: [darkly, themes/index.css, themes/dark.scss, themes/dark-default.scss]
  light: [flatly, themes/index.css]
