---
project:
  type: website
  output-dir: demo-data
  preview:
    port: 3000
    browser: false
lib-dir: ./assets
jupyter: python3
website:
  title: "acederberg's data science blog"
  site-url: https://quarto.acederberg.io
  description: "acederberg's quarto projects"
  navbar:
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      # - icon: rss
      #   href: index.xml
      - text: acederberg.io
        href: https://acederbeg.io
style: 
  html:
    theme: index.scss
