---
image: https://avatars.githubusercontent.com/u/77076023?v=4
about:
  template: jolla
  links: 
    - icon: github
      text: Github
      href: 'https://github.com/acederberg'
    - icon: linkedin
      text: LinkedIn
      href: 'https://www.linkedin.com/in/adrian-cederberg-b453571b9/'
    - icon: twitter
      text: Twitter
      href: 'https://x.com/_acederberg'
listing:
  # - id: links
  #   fields:
  #     - title
  #   type: grid
  #   image-height: 128px;
  #   contents:
  #     - ./resume.qmd
  #     - ./about.qmd
  #     - ./projects.qmd
  - id: categories
    fields:
      - title
      - date
      - image
      - author
    type: grid
    image-height: 256px
    sort:
      - date desc
    contents:
      - ./posts/index.qmd
      - ./dsa/leetcode/index.qmd
      - ./kaggle/index.qmd
  - id: posts
    fields:
      - title
      - date
      - image
      - author
    type: grid
    image-height: 256px
    sort:
      - date desc
    contents:
      - ./posts/logistic
      - ./posts/python-animation
      - ./posts/quarto-kube-static
      - ./posts/include-code-files
date-updated: 10-01-2024
---


:::{#jolla}
I am Adrian Cederberg and this is my blog powered by [quarto](https://quarto.org).
I have a Bachelors of Science in Applied Mathematics from the University of New Mexico and a wide range of experience including teaching, research, and software development. 
My technical interests include mathematics, physics, and software.
Lately I am interested in writing software as I have found it to be an indispensable skill in the various topics which interest me.

Blog posts will vary in subject matter, but invariably pertain to topics in computer science.
Some things I will write about are ``python``, data structures and algorithms, containerization, infrastructure as code, numerical mathematics, and data science.
For inquiries, please reach out to me at ``adrn.cederberg123@gmail.com`` or ``@_acederberg`` on twitter. 
If you find any errors in my blog posts, please make an issue on [the github repository for this wibsite](https://github.com/acederberg/quarto-maths).
:::


## Categories

:::{#categories}
:::


## Posts

:::{#posts}
:::


## Github Statistics

<div id="commits">
  <script src="https://cdn.rawgit.com/IonicaBizau/github-calendar/gh-pages/dist/github-calendar.min.js"></script>
  <div class="calendar"></div>
  <script>
      new GitHubCalendar(".calendar", "acederberg", {global_stats: false, summary_text: null});
  </script>
</div>


## Where is the Old Blog?

This site deprecates my previous blog, for which I made the [captura-text](https://github.com/acederberg/captura-text) plugin.
The content on the deprecated site can be found in [another repo](https://github.com/acederberg/captura-text-portfolio-assets).
