[tool.poetry]
name = "quarto-demo"
version = "0.0.0"
description = "Quarto demo"
authors = ["Adrian Cederberg <adrn.cederberg123@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.0.0"
seaborn = "^0.13.2"
jupyter = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
