[tool.poetry]
name = "quarto-demo"
version = "0.0.0"
description = "Quarto demo"
authors = ["Adrian Cederberg <adrn.cederberg123@gmail.com>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.0.0"
seaborn = "^0.13.2"
jupyter = "^1.0.0"
pandas = "^2.2.2"
shiny = "^0.10.2"
shinywidgets = "^0.3.2"
jupyter-cache = "^1.0.0"
shinylive = "^0.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
