---
title: How to Include Python Code From Files in Quarto
description: Make it possible to import outside code into your quarto notebooks.
image: /icons/quarto.svg
extra:
  url: /examples/include-code-files
  image: /icons/quarto.svg
keywords:
  - quarto
  - python
  - include code
  - external code
  - datascience
  - data
  - science
date: 2024-08-31
date-modified: 2024-08-31
---


It is possible to include code files using the [include-code-files]( https://github.com/quarto-ext/include-code-files) extension for quarto.
For more on adding extensions, see [the documentation about extensions management](https://quarto.org/docs/extensions/managing.html).


## Including Files

First, in the front matter of your quarto document, add 


```yaml
filters:
  - include-code-files
```


Next, create ``example.py``  with the contents


```{.python include="example.py"}
```

and ensure that ``example.py`` works using


```sh
python ./example.py
```


To include this file in simply do:


````quarto
```{.python include="example.py"}
```
````


which should render to


```{.python include="example.py"}
```


## Running Files

``example.py`` can be run using the ``run`` jupyter magic commands like:


````quarto
```{python}
%run example.py
```
````


More about magic commands is available in the [jupyter documentation](https://ipython.readthedocs.io/en/stable/interactive/magics.html).
Finally, with ``main`` in the local python globals, we can execute ``main``.


````quarto
```{python}
main()
```
````


## Including Snippets From Files

Often, including the whole file is not desirable and only a part of the file 
should be included. For instance if the conents of ``example.py`` are modified
to make it


```python
# start snippet main
def main():
    print("It works!")
    # end snippet main


if __name__ == "__main__":
    main()
```


the following code block in quarto will only include the ``main`` function 
definition.


````quarto
```{.python include="eample.py" snippet="print"}
```
````
