---
apiVersion: apps/v1
metadata:
  namespace: blog
  name: blog
  labels:
    acederberg.io/tier: browser
    acederberg.io/from: kubectl
    acederberg.io/component: blog
kind: Deployment
spec:
  selector:
    matchLabels:
      acederberg.io/tier: browser
      acederberg.io/from: kubectl
      acederberg.io/component: blog
  template:
    metadata: 
      labels:
        acederberg.io/tier: browser
        acederberg.io/from: kubectl
        acederberg.io/component: blog
    spec:
      containers:
        - name: blog
          image: acederberg/blog:latest
          imagePullPolicy: Always
          ports: 
            - name: captura-http
              containerPort: 8080
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1




