---
services:
  server:
    build:
      context: ..
      dockerfile: ./docker/dockerfile
      target: production
    image: acederberg.io/quarto-blog-production:0.0.1
    ports:
      - published: 8080
        target: 8080
    tty: true
    # command: ["sh"]
    command: [
      "npx", 
      "http-server", 
      "--port", "8080", 
      "--robots", "--proxy", 
      "https://errors.acederberg.io/404.html", "/app"
    ]
