---
services:
  server:
    build:
      context: ..
      dockerfile: ./docker/dockerfile
      target: production
      secrets:
        - source: kaggle_json
    image: acederberg/blog:${SERVER_VERSION-0.1.1}
    ports:
      - published: 8080
        target: 8080
    tty: true

secrets:
  kaggle_json:
    file: ../config/kaggle/kaggle.json
    external: true

