# render: incremental
project:
  type: website
  resources:
    - ./robots.txt
    - ./posts/**/*.png
    - ./icons/test.json
    - ./icons/kubernetes.json
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
jupyter: python3
website:
  page-navigation: true
  title: acederberg.io
  site-url: https://acederberg.io
  description: acederberg's blog.
  repo-url: https://github.com/acederberg/quarto-maths
  sidebar:
    # NOTE: Too messy!
    # - id: leetcode
    #   section: LeetCode
    #   href: ./dsa/leetcode
    #   contents: ./dsa/leetcode

    - id: projects
      title: Projects
      style: "docked"
      contents:
        - section: Projects
          href: ./projects
          contents:
            - text: '---'
            - section: Blog
              contents:
                - text: Why Even Have a Blog?
                  href: ./projects/blog/index.qmd
                - text: '---'
                - text: 'Subproject: Resume Hosted on the Blog'
                  href: ./resume/index.qmd
                - text: 'Subproject: Leetcode Problems'
                  href: ./dsa/leetcode/index.qmd
                - text: '---'
                - text: 'Details: Blog ReadMe'
                  href: ./projects/blog/instructions.qmd
                - text: 'Details: How is the Blog Deployed?'
                  href: ./projects/blog/deploy.qmd
                  # NOTE: These contents should supplimental blog posts.
                  contents:
                    - text: Static Sites in Kubernetes
                      href: ./posts/quarto-kube-static/index.qmd

            - text: '---'
            - title: Nvim Configuration
              href: ./projects/nvim-config/index.qmd

            - text: '---'
            - section: Blog and Demo Automation
              href: ./projects/automation
              contents:
                - title: Blog and Demo Infrastructure as Code on Linode
                  href: ./
                - title: Github Actions
                  href: ./projects/

  # NOTE: https://icons.getbootstrap.com/
  navbar:
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - text: Home
        href: /
      - sidebar:projects
      - text: Resume
        href: https://acederberg.io/resume
      - text: Posts
        href: /posts
      - text: Kaggle
        href: /kaggle
      - text: Leetcode
        href: /dsa/leetcode
theme:
  dark: [cyborg, ./themes/commits.css, ./themes/index.css, ./themes/dark.scss, ./themes/dark-default.scss]
  light: [cosmo, ./themes/commits.css, ./themes/index.css]
format:
  html:
    code-fold: false
    embed-resources: false
    template-partials:
      - templates/metadata.html

author:
  - name: Adrian Cederberg
    url: acederberg.io
    email: adrn.cederberg123@gmail.com
filters:
  - include-code-files
execute:
  freeze: true
  cache: true
toc: true
toc-depth: 3
