# render: incremental
project:
  type: website
  resources:
    - ./robots.txt
    - ./posts/**/*.png
    - ./icons/**/*.json
    - ./js/*.js
    - build.json
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
jupyter: python3
# NOTE: This is currently half baked, and documentation will not be completed
#       for quite a while. This is being added for the sake of completeness of
#       the components demos/docs since js docs already exist.
quartodoc:
  title: acederberg.io
  package: acederbergio
  dir: ../blog/projects/blog/quartodoc
  parser: sphinx
  rewrite_all_pages: true
  options: {}
  sections:
    - title: Quarato Filters
      desc: Custom filters utilitized by quarto.
      contents:
        - name: overlay
          package: acederbergio.filters
        - name: floaty
          package: acederbergio.filters
        - name: live
          package: acederbergio.filters
        - name: resume
          package: acederbergio.filters
        - name: iframe
          package: acederbergio.filters

    - title: Utilities
      desc: Utilities for building and writing filters and API endpoints.
      options:
        exclude: [cli_show_environ, cli_show_logging, cli_find, cli]
      contents:
        - name: env
        - name: util
        - name: iconify

    - title: Development API
      desc: Development Mode API
      options:
        exclude: []
      contents:
        - name: quarto
          package: acederbergio.api


  # - title: API Documentation
  #   desc: API Documentation Beyond that Provided by Swagger.
  #   contents:
  #     - name: api.schemas


website:
  favicon: ./icons/favicon.svg
  twitter-card:
    creator: _acederberg
  open-graph: true
  page-navigation: true
  title: acederberg.io
  site-url: https://acederberg.io
  description: acederberg's blog.
  repo-url: https://github.com/acederberg/quarto-maths
  sidebar:
    - id: components
      border: true
      title: Components and Filters
      style: "docked"
      contents:
        - section: IFrames
          contents:
            - text: Demo
              href: ./components/iframe/index.qmd
            - text: "Docs: Pandoc Filter"
              href: "./projects/blog/quartodoc/iframe.qmd"
        - section: Overlay
          contents:
            - text: Demo
              href: ./components/overlay/index.qmd
            - text: "Docs: Pandoc Filter"
              href: "./projects/blog/quartodoc/overlay.qmd"
            - text: "Docs: Javascript"
              href: "./projects/blog/typedoc/overlay.qmd"
        - section: Floaty
          contents:
            - text: "Demo: Overview"
              href: ./components/floaty/index.qmd
            - text: "Demo: Skills"
              href: ./components/floaty/skills.qmd
            - text: "Demo: Contacts"
              href: ./components/floaty/contacts.qmd
            - text: "Demo: Links"
              href: ./components/floaty/links.qmd
            - text: "Demo: Under Construction"
              href: ./components/floaty/under-construction.qmd
            - text: "Docs: Pandoc Filter"
              href: "./projects/blog/quartodoc/floaty.qmd"
            - text: "Docs: Javascript"
              href: "./projects/blog/typedoc/floaty.qmd"
        - section: Resume
          contents:
            - text: Demo
              href: ./components/resume/index.qmd
            - text: "Docs: Pandoc Filter"
              href: "./projects/blog/quartodoc/resume.qmd"
    - id: projects
      title: Projects
      style: "docked"
      contents:
        - section: Projects
          href: ./projects
          contents:
            - section: Blog
              contents:
                - text: About the Blog
                  href: ./projects/blog/index.qmd
                - section: Subprojects
                  contents:
                    - text: 'Resume'
                      href: ./resume/about.qmd
                    - text: 'Building A Custom Iconset for Kubernetes'
                      href: ./posts/iconify/index.qmd
                    - text: 'Leetcode Problems'
                      href: ./dsa/leetcode/index.qmd

                - section: Technical Details
                  contents:
                    - text: 'Blog ReadMe'
                      href: ./projects/blog/instructions.qmd
                    - text: 'Docker and Quarto'
                      href: ./projects/blog/build.qmd
                    - text: 'How is the Blog Deployed?'
                      href: ./projects/blog/deploy.qmd
                    - text: Static Quarto Websites in Kubernetes
                      href: ./posts/quarto-kube-static/index.qmd

            - section: Nvim Configuration
              contents:
                - title: Why Even Use Neovim?
                  href: ./projects/nvim-config/index.qmd
                - title: Gallery
                  href: ./projects/nvim-config/gallery.qmd

            - section: Blog and Demo Automation
              contents:
                - title: Blog and Demo Infrastructure as Code on Linode
                  href: ./projects/automation/index.qmd

                - title: Blog and Demo Github Actions
                  href: ./projects/automation/actions.qmd

            - section: Captura
              contents:
                - title: What is Captura?
                  href: ./projects/captura/index.qmd

                - title: Projects I am Building onto of Captura
                  href: ./projects/captura/about.qmd

  # NOTE: https://icons.getbootstrap.com/
  navbar:
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - text: Home
        href: /
      - sidebar:projects
      - text: Resume
        href: /resume
      - text: Posts
        href: /posts
      - text: Kaggle
        href: /kaggle
      - text: Leetcode
        href: /dsa/leetcode
theme:
  light:
    - themes/extras.scss
    - cosmo
    - themes/live.scss
    - themes/floaty.scss
    - themes/index.scss
    - themes/overlay.scss
    - themes/resume.scss
format:
  html:
    layout: full-page
    code-fold: false
    embed-resources: false
    # template-partials:
    #   - templates/metadata.html
    include-in-header:
      - file: ./includes/iconify.html
      - file: ./includes/external_links.html
      - file: ./includes/overlay.html
      - file: ./includes/floaty.html
      - file: ./includes/live.html

author:
  - name: Adrian Cederberg
    url: acederberg.io
    email: adrn.cederberg123@gmail.com

filters:
  - include-code-files
  - iconify
  - quarto
  - ./filters/live.py
  - ./filters/overlay.py
  - ./filters/floaty.py

execute:
  freeze: true
  cache: true
toc: true
toc-depth: 3
