project:
  type: website
  resources:
    - ./robots.txt
    - ./posts/**/*.png
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
jupyter: python3
website:
  page-navigation: true
  title: acederberg.io
  site-url: https://acederberg.io
  description: acederberg's blog.
  repo-url: https://github.com/acederberg/quarto-maths
  sidebar:
    - id: projects
      title: Projects
      style: "docked"
      contents:
        - section: Projects
          href: ./projects
          contents:
            - section: Blog
              contents:
                - text: About
                  href: ./projects/blog/index.qmd
                - text: Technical Details
                  href: ./projects/blog/readme.qmd
            - title: Nvim Configuration
              href: ./projects/nvim-config/index.qmd

  # NOTE: https://icons.getbootstrap.com/
  navbar:
    # background: default
    # foreground: '#000'
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - text: Home
        href: /
      - sidebar:projects
      - text: Posts
        href: /posts
      - text: Kaggle
        href: /kaggle
      - text: Leetcode
        href: /dsa/leetcode
      - text: Resume
        href: https://acederberg.io/resume
theme:
  dark: [cyborg, ./themes/commits.css, ./themes/index.css, ./themes/dark.scss, ./themes/dark-default.scss]
  light: [cosmo, ./themes/commits.css, ./themes/index.css]
format:
  html:
    code-fold: false
    embed-resources: false
    template-partials:
      - templates/metadata.html
author:
  - name: Adrian Cederberg
    url: acederberg.io
    email: adrn.cederberg123@gmail.com
filters:
  - include-code-files
execute:
  freeze: true
  cache: true
toc: true
toc-depth: 3
