# render: incremental
project:
  type: website
  resources:
    - ./robots.txt
    - ./posts/**/*.png
    - ./icons/**/*.json
    - ./js/*.js
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
jupyter: python3
website:
  favicon: ./icons/favicon.svg
  page-navigation: true
  title: acederberg.io
  site-url: https://acederberg.io
  description: acederberg's blog.
  repo-url: https://github.com/acederberg/quarto-maths
  sidebar:
    - id: projects
      title: Projects
      style: "docked"
      contents:
        - section: Projects
          href: ./projects
          contents:
            - text: '---'
            - section: Blog
              contents:
                - text: About the Blog
                  href: ./projects/blog/index.qmd
                - section: Subprojects
                  contents:
                    - text: 'Resume'
                      href: ./resume/about.qmd
                    - text: 'Building A Custom Iconset for Kubernetes'
                      href: ./posts/iconify/index.qmd
                    - text: 'Leetcode Problems'
                      href: ./dsa/leetcode/index.qmd

                - section: Technical Details
                  contents:
                    - text: 'Blog ReadMe'
                      href: ./projects/blog/instructions.qmd
                    - text: 'Docker and Quarto'
                      href: ./projects/blog/build.qmd
                    # - text: 'Quality Assurence'
                    #   href: ./projects/blog/qa.qmd
                    - text: 'How is the Blog Deployed?'
                      href: ./projects/blog/deploy.qmd
                    - text: Static Quarto Websites in Kubernetes
                      href: ./posts/quarto-kube-static/index.qmd

            - text: '---'
            - section: Nvim Configuration
              contents:
                - title: Why Even Use Neovim?
                  href: ./projects/nvim-config/index.qmd
                - title: Gallery
                  href: ./projects/nvim-config/gallery.qmd
                  # - title: Configuration ReadMe
                  #   href: ./projects/nvim-config/instructions.qmd



            - text: '---'
            - section: Blog and Demo Automation
              contents:
                - title: Blog and Demo Infrastructure as Code on Linode
                  href: ./projects/automation/index.qmd

                - title: Blog and Demo Github Actions
                  href: ./projects/automation/actions.qmd

            - text: '---'
            - section: Captura
              contents:
                - title: What is Captura?
                  href: ./projects/captura/index.qmd

                - title: Projects I am Building onto of Captura
                  href: ./projects/captura/about.qmd

  # NOTE: https://icons.getbootstrap.com/
  navbar:
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - text: Home
        href: /
      - sidebar:projects
      - text: Resume
        href: /resume
      - text: Posts
        href: /posts
      - text: Kaggle
        href: /kaggle
      - text: Leetcode
        href: /dsa/leetcode
theme:
  # dark: [cyborg, ./themes/commits.css, ./themes/index.css, ./themes/dark.scss, ./themes/dark-default.scss]
  light: [cosmo, ./themes/commits.css, ./themes/index.css, ./themes/overlay.css, ./themes/floaty.scss, ./themes/resume.scss]
format:
  html:
    code-fold: false
    embed-resources: false
    template-partials:
      - templates/metadata.html
    include-in-header:
      - file: ./includes/iconify.html
      - file: ./includes/external_links.html
      - file: ./includes/overlay.html

author:
  - name: Adrian Cederberg
    url: acederberg.io
    email: adrn.cederberg123@gmail.com
filters:
  - include-code-files
  - iconify
execute:
  freeze: true
  cache: true
toc: true
toc-depth: 3
