project:
  type: website
  resources:
    - ./robots.txt
    - ./posts/**/*.png
  output-dir: build
  preview:
    host: 0.0.0.0
    port: 3000
    browser: false
jupyter: python3
website:
  title: acederberg.io
  site-url: https://acederberg.io
  description: acederberg's blog.
  # NOTE: https://icons.getbootstrap.com/
  navbar:
    background: success
    foreground: '#222'
    right:
      - icon: github
        href: https://github.com/acederberg
      - icon: linkedin
        href: https://www.linkedin.com/in/adrian-cederberg-b453571b9/
      - icon: twitter
        href: https://x.com/_acederberg
    left:
      - text: Home
        href: /
      - text: Kaggle
        href: /kaggle
      - text: Posts
        href: /posts
      - text: Leetcode
        href: /dsa/leetcode
        # - text: Resume
        #   href: https://acederberg.io/resume
theme:
  dark: [darkly, ./themes/commits.css, ./themes/index.css, ./themes/dark.scss, ./themes/dark-default.scss]
  light: [flatly, ./themes/commits.css, ./themes/index.css]
format:
  html:
    code-fold: false
    embed-resources: false
    template-partials:
      - templates/metadata.html
author:
  - name: Adrian Cederberg
    url: acederberg.io
    email: adrn.cederberg123@gmail.com
filters:
  - include-code-files
execute:
  freeze: true
  cache: true
toc: true
toc-depth: 3
