---
title: Floaty Storybook
contents: true
live_reload: true
live_depends_on:
  - blog/includes/temp.html
format:
  html:
    layout: full-page
floaty:
  floaty-bg-grow-shadow:
    container:
      include_titles: true
      classes:
        - floaty
        - floaty-size-1
        - floaty-hover
        - floaty-shadow-2
        - floaty-bg-light
        - py-5
      classes_rows:
        - "py-5"
    content:
      - image:
          iconify:
            set: misc
            name: quarto
        key: quarto
        title: Quarto
      - null
      - image:
          iconify:
            set: devicon
            name: latex
        key: latex
        title: Latex
      - null
      - image:
          iconify:
            set: devicon
            name: pulumi
        key: pulumi
        title: Pulumi
      - null
      - image:
          iconify:
            set: logos
            name: github-icon
        key: github
        title: Github
      - null
      - image:
          iconify:
            set: devicon
            name: git
        key: git
        title: Git

  floaty-bg-card-grow-shadow:
    container:
      include_titles: true
      classes:
        - floaty
        - floaty-size-3
        - floaty-hover
        - floaty-shadow-3
        - floaty-card-bg-light
        - py-5
      classes_rows:
        - "py-5"
      classes_items:
        - px-1

    content:
      - image:
          iconify:
            set: devicon
            name: neovim
        key: neovim
        title: Neovim
      - null
      - image:
          iconify:
            set: devicon
            name: python-wordmark
        key: python
        title: Python
      - null
      - image:
          iconify:
            set: devicon
            name: nodejs-wordmark
        key: nodejs
        title: Nodejs
      - null
      - image:
          iconify:
            set: misc
            name: mermaid
        key: mermaid
        title: Mermaidjs
        description: |
          For making some terrific diagrams.
      - null
      - image:
          iconify:
            set: logos
            name: linode
        key: linode
        title: Linode
        description: |
          This is where the servers live.

  floaty-bootstrap:
    mode: bootstrap
    overlay:
      identifier: floaty-bootstrap-overlay
      colorize:
        color: teal
        color_text: black
        color_text_hover: white
    container:
      columns: 0
      include_titles: false
      classes:
        - floaty
        - floaty-size-5
        - floaty-hover
        - floaty-shadow-2
        - floaty-bg-light
        - py-2
      classes_rows:
        - "py-5"
      classes_items:
        - px-1
        - text-teal
    content:
      - image:
          bootstrap:
            name: filetype-py
        title: Python
        key: py
      - image:
          bootstrap:
            name: filetype-js
        title: Javascript
        key: js
      - image:
          bootstrap:
            name: filetype-html
        title: HTML
        key: html
      - image:
          bootstrap:
            name: filetype-yml
        title: YAML
        key: yaml
      - image:
          bootstrap:
            name: file-earmark-pdf
        title: PDF
        key: pdf
      - image:
          bootstrap:
            name: alarm
        title: Alaram
        key: alarm
  floaty-rows:
    mode: bootstrap
    container:
      classes:
        - floaty-hover
      columns: -1
      include_titles: true
    content:
      - title: Phone
        key: phone
        value: (505) 589 - 6914
        image:
          font_awesome: faPhone
          bootstrap:
            name: phone

      - title: Email
        key: email
        value: adrn.cederberg123@gmail.com
        font_awesome: faEnvelope
        image:
          bootstrap:
            name: envelope

      - title: Location
        key: location
        value: Albuquerque, NM
        font_awesome: faLocationArrow
        image:
          bootstrap:
            name: compass
---

## Pure {{< iconify devicon html5 >}} `HTML` and {{< iconify devicon css3 >}}`CSS` Floaty

A minimal floaty should:

- have icons layed out in a nice `2 X 2` grid,
- have no hover effects or backgrounds/shadows behind icons or cards,
- set the cursor to a pointer to suggest clicking.

```{=html}
{{< include ./includes/temp.html >}}
```

::: { .callout-note collapse=true }

### HTML Code

```{.html include=./includes/temp.html snippet="html"}

```

:::

## Floaties Generated by Pandoc Filter {{< iconify devicon python >}}

### Images With Background and Hover Effect

The following should have icons with

1. a background with rounded corners,
2. shadows on icons,
3. and grow on hover - when hovered, there should be no background.

and cards that

1. Have content that do not transform when hovered,
2. Have no shadows.

::: { #floaty-bg-grow-shadow }

:::

### Cards With Background and Hover Effect

The following should have cards with

1. a background with rounded corners,
2. and shadows on background,
3. no hover effects.

::: { #floaty-bg-card-grow-shadow }

:::

Equal spacing and size of cards may be achieved by adding `null` list items
to pandoc metadata, e.g. the following should create a diagonal in a `3 X 3`
grid

::: { .callout-note collapse=true }

#### YAML Metadata For Null Blocks

```yaml
floaty:
  my-elem-id:
    container:
      include_titles: true
      classes:
        - floaty
        - floaty-size-3
        - floaty-card-bg-light
        - floaty-card-shadow-3
        - py-5
      classes_rows:
        - "py-5"
      classes_items:
        - px-1

    content:
      # NOTE: Row 1
      - image:
          iconify:
            set: devicon
            name: neovim
        key: neovim
        title: Neovim
      - null
      - null

      # NOTE: Row 2
      - null
      - image:
          iconify:
            set: devicon
            name: python-wordmark
        key: python
        title: Python
      - null

      # NOTE: Row 3
      - null
      - null
      - image:
          iconify:
            set: devicon
            name: nodejs-wordmark
        key: nodejs
        title: Nodejs
```

:::

### Bootstrap Icons in a Single Row

The following content:

1. should appear in a single row,
2. should not have an titles,
3. use bootstrap icons, shown in red,
4. include an overlay that opens when cards are clicked.

<!----------------------------------------------------------------------------> ::: { #floaty-bootstrap-overlay }

::: { .overlay-content-item .p-5 data-key=py}

#### Python

:::

::: { .overlay-content-item .p-5 data-key=js}

#### Javascript

:::

::: { .overlay-content-item .p-5 data-key=html}

#### HTML

:::

::: { .overlay-content-item .p-5 data-key=yaml}

#### YAML

:::

::: { .overlay-content-item .p-5 data-key=pdf}

#### PDF

:::

::: { .overlay-content-item .p-5 data-key=alarm}

#### Alarm

:::

<!----------------------------------------------------------------------------> :::

::: { #floaty-bootstrap }

:::

::: { .callout-note collapse=true }

#### Using Bootstrap Mode, Disabling Titles, and Single Rows

To enable bootstrap mode, use `mode: bootstrap` in the floaty configuration.
Settings columns to `0` should put everything into a single row unless more than `1000` icons are specified.
To disable titles, set `include_titles` to `false`.

```yaml
floaty:
  floaty-bootstrap:
    mode: bootstrap
    container:
      columns: 0
      include_titles: false
      classes:
        - floaty
        - floaty-size-5
        - floaty-hover
        - floaty-shadow-2
        - floaty-bg-light
        - py-2
      classes_rows:
        - "py-5"
      classes_items:
        - px-1
        - text-teal
    content:
      - image:
          bootstrap:
            name: filetype-py
        title: Python
      - image:
          bootstrap:
            name: filetype-js
        title: Javascript
      - image:
          bootstrap:
            name: filetype-html
        title: HTML
      - image:
          bootstrap:
            name: filetype-yml
        title: YAML
      - image:
          bootstrap:
            name: file-earmark-pdf
        title: PDF
      - image:
          bootstrap:
            name: alarm
        title: Alaram
```

:::

### Bootstrap Icons in Rows

A prototype for rows. Currently, this does not work as I would like and I would
prefer a pure `CSS` implementation for putting the image on the left.

::: { #floaty-rows .py-5 }

:::

This can be enabled by setting `columns` to a negative value.
