---
title: My Blog
format:
  html:
    include-in-header:
      - file: ../../includes/overlay.html
filters:
  - ../../filters/floaty.py
floaty:
  thank-you-tools:
    tooltip:
      include: true
    container:
      size_item: 128 # px
      size_item_margin: 32
      kind: list
    overlay:
      include: true
      size_icon: 256
    content:
      - image:
          iconify:
            set: misc
            name: quarto
        key: quarto
        title: Quarto
      - image:
          iconify:
            set: devicon
            name: latex
        key: latex
        title: Latex
      - image:
          iconify:
            set: devicon
            name: pulumi
        key: pulumi
        title: Pulumi
      - image:
          iconify:
            set: logos
            name: github-icon
        key: github
        title: Github
      - image:
          iconify:
            set: devicon
            name: git
        key: git
        title: Git
      - image:
          iconify:
            set: devicon
            name: neovim
        key: neovim
        title: Neovim
      - image:
          iconify:
            set: devicon
            name: python-wordmark
        key: python
        title: Python
      - image:
          iconify:
            set: devicon
            name: nodejs-wordmark
        key: nodejs
        title: Nodejs
      - image:
          iconify:
            set: misc
            name: mermaid
        key: mermaid
        title: Mermaidjs
        description: |
          For making some terrific diagrams.
      - image:
          iconify:
            set: logos
            name: linode
        key: linode
        title: Linode
        description: |
          This is where the servers live.
      - image:
          iconify:
            set: logos
            name: kubernetes
        key: kubernetes
        title: Kubernetes
      - image:
          iconify:
            set: devicon
            name: pandas-wordmark
        key: pandas
        title: Pandas
      - image:
          iconify:
            set: devicon
            name: kaggle-wordmark
        key: kaggle
        title: Kaggle
      - image:
          iconify:
            set: devicon
            name: docker-wordmark
        key: docker
        title: Docker
---

Here I discuss the implementation of this blog itself as it has been quite a project to do so.
This is my blog that you are likely viewing this on.
In my time making this, I have learned quite a bit about [quarto](https://quarto.org) {{< iconify misc quarto >}},
an amazing markup and notebook format for websites, jupyter notebooks, books, articles, and more.
Almost all blog pages and navigation in this blog is authored using quarto.

In this time, I have also had quite some fun figuring out how to to implement

- continuous integration and continuous deployment for this project using github actions {{< iconify logos github-actions>}},
- a `docker` {{< iconify logos docker-icon >}} image that accomodates `kaggle` {{< iconify logos kaggle >}} api calls and mounting of other secrets duing the build using secrets,
- and how to create diagrams with [mermaid {{< iconify misc mermaid >}}](https://mermaid.js.org) and [iconify](https://iconify.design).

Further, there are associated projects (in the sidebar) that support this project.
For instance

- the [my neovim configuration](../nvim-config/index.qmd) is designed to make editing `quarto` documents very easy,
- and the [infrastructure and automation project](../automation) where [pulumi {{< iconify logos pulumi-icon >}}](https://pulumi.com/) and `python` {{< iconify logos python >}} are used to [deploy](./deploy.qmd) the infrastructure to linode {{< iconify logos linode >}}.

## The Tools That Make it Possible

Thank you to all of the contributors to the tools I have used that made this possible at all!
I cannot emphasize enought that without the tremendous efforts of the open source community (in particular) that this would not be possible at all.
Click on any of the icons below to see a brief description of how each tool is utilitized here.

:::::: { #thank-you-tools }

<!-- start overlay --> ::::: { .overlay }
<!-- start overlay-content --> :::: { .overlay-content }

::: { .overlay-content-item data-key="quarto" }

Quarto is an excellent code notebook built on top of pandoc.
It can convert `.qmd` documents to
<iconify-icon icon="devicon:latex"></iconify-icon> `latex`,
<iconify-icon icon="devicon:html5"></iconify-icon> `html`, and more.
It is the backbone of this project and most of the documents
presented are rendered `.qmd` documents and some pandoc filters.

:::

::: { .overlay-content-item data-key="latex" }

Without TeX, I would have to write my resume in Microsoft word.
Since I do all of my work on a linux machine, I could have used libre
word, however I generally like not to use such tools since they do
not produce documents that play well with git
{{< iconify devicon git >}}.

**Using a GUI text editor - This is one of the few fates I believe to
be worse than death.**

:::

::: { .overlay-content-item data-key="pulumi" }

Pulumi is a great infrastructure as code tool available in most
popular lanugages. I use it to provision the kubernetes cluster
that this blog runs on and set up paripheral resources. I also use
it to manage kubernetes resources, such as traefik and the error
pages. <iconify-icon icon="logos:kubernetes"></iconify-icon>

:::

::: { .overlay-content-item data-key="github" }

Github is where I host all of my code.

:::

::: { .overlay-content-item data-key="git" }

Git is a fantastic tool for version control.
Without version control, software development would be very tedious.
It allows me to make experimental changes and revert to my last point
in my work and maintain multiple working versions of the same
project.

:::

::: { .overlay-content-item data-key="neovim" }

My favorite tool for text editing.

:::

::: { .overlay-content-item data-key="python" }

The primary language I use in my quarto notebooks.

:::

::: { .overlay-content-item data-key="nodejs" }

My server uses `http-server` to deliver these html pages.

:::

::: { .overlay-content-item data-key="kubernetes" }

This is where the containers run.

:::

::: { .overlay-content-item data-key="pandas" }

This is my favorite tool for loading an manipulating datasets in
python {{< iconify devicon python >}}.

:::

::: { .overlay-content-item data-key="kaggle" }
The data science competition platform.
:::

::: { .overlay-content-item data-key="docker" }

The containerization technology used to gaurentee consistent builds
in github actions and a uniform development environment.

:::

<!-- stop overlay-content --> ::::
<!-- stop overlay-content-item --> :::::

:::::

## Thank You to the Reviewers

Thank you to all of my reviewers for their hard work in reviewing and consulting:

::: {}

- [Chris "that Chris" Sanchez]()
- John "Bud" Poston

:::

## Why Have a Blog?

I have always been really into taking notes, so I thought it would be good to get away from paper.
Working with web pages offers much more flexibility a features than using paper notes and allows me to share them with ease.

### About `leetcode`

::: { #leetcode-icon .floaty-container-single }

::: { .floaty }

{{< iconify misc leetcode-02 size=256px >}}

:::

:::

Data structures and algorithms is a useful subject matter to be knowledgable about in computer science and software.
Additionally, the subject matter is frequently quized in SDE technical interviews.
Since I am currently applying for jobs and working on `leetcode` problems, I figured I should start to do some for practice.
I also wanted to have a record of the problem which I had done and to take more extensive notes on the things that I did not understand or found interesting.

### About the Resume

::: { #leetcode-icon .floaty-container-single }

::: { .floaty }

{{< iconify misc quarto size=256px >}}

:::

:::

I thought it might be helpful to have all of the resumes I distribute contain a link to the most recent version of [my resume](/resume).
To make this possible, I would have to host it somewhere and thought my blog would be the most suitable place.
This came with a number of benefits, such as

- having version control over my resume,
- rendering into multiple formats like `TeX`, `PDF`, and `HTML`,
- integration of the resume into something I'd be working on frequently,
- being able to edit in my favorite tool `nvim` instead of [overleaf](https://overleaf.com),
- having the projects described in the resume have corresponding pages on the same website,
- having auxilary content available for the resume when everything might not fit.

### About the Projects

::: { #leetcode-icon .floaty-container-single }

::: { .floaty }

{{< iconify devicon github size=256px >}}

:::

:::

I've made a few projects (including this blog) which I wanted to showcase here.
Each of these will have their own page dedicated them, and should be available in the sidebar.
For some of the larger projects there might be extensive documentation.

To learn more about the technical details, see the subsequent pages.
