name: Build and Deploy
on:
  workflow_dispatch:
jobs:
  # NOTE: See [the example](https://github.com/marketplace/actions/build-and-push-docker-images).
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Build Server Image.
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfile
          target: builder
          tags: acederberg/blog:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

  kube:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    permissions:   
      id-token: write   
      contents: read   
      actions: read
    steps:
      - name: Checkout.
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # NOTE: It is required to apply ``./docker/manifests/sa.yaml`` and 
      #       generate credentials for that service account, e.g.
      #       ``kubectl create token ...``.
      - uses: azure/k8s-set-context@v1
        with:
          method: serviceaccount
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SA_TOKEN }}
        id: setcontext

      # NOTE: Correct imagePullPolicy is necessary for this step to work. 
      #       Specifying the image version requires special permissions so that
      #       the action can modify workflow files, thus the latest tag is 
      #       used.
      - uses: Azure/k8s-deploy@v5
        with:
           namespace: blog
           manifests: docker/manifests/ci.yaml
