name: Build and Deploy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout.
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx.
        uses: docker/setup-buildx-action@v3

      - name: Build Server Image.
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/dockerfile
          target: builder
          tags: acederberg/quarto-blog:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

  # kube:
  #   name: Deploy to Kubernetes
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
